---

## https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: 'node_js'
node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - 'node'

install:
  - 'make dependencies-user-wide-get'
  - 'make dependencies-get'
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install -qq oracle-java8-installer'
  - 'sudo update-java-alternatives -s java-8-oracle'
  - 'sudo pip install html5validator yq'

script:
  - "make NODEJS=node check-full"
