---

## https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: 'node_js'
node_js:
  - '0.12.3'
  - '0.12'
  - '4'
  - '5'
  - '6'
  - '7'

  # Seems NodeJS v8 support is currently broken for some reason:
  # https://travis-ci.org/opening-hours/opening_hours.js/jobs/282669934#L665-L677
  # - 'node'

install:
  - 'make dependencies-user-wide-get'
  - 'make dependencies-get'
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install -qq oracle-java8-installer'
  - 'sudo update-java-alternatives -s java-8-oracle'
  - 'sudo pip install html5validator'

script:
  - "make NODEJS=node check-full"
