---
# SPDX-FileCopyrightText: 2021 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Continuous Integration
'on':
  - 'push'
  - 'pull_request'

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    strategy:
      matrix:
        node-version:
          # Support policy: We support every Node.js version is still "maintained".
          # Testing unmaintained versions serves no purpose.

          # The only exception is that the oldest Node.js version under which all tests
          # pass is still tested but can be increased as needed.
          - '8.x'

          - '12.x'
          - '14.x'
          - '15.x'

    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add ~/.local/bin to $PATH
        run: 'printf "%s/.local/bin\n" "${HOME}" >> ${GITHUB_PATH}'

      - run: make dependencies-user-wide-get
      - run: make dependencies-get

      - run: make check-full
